name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build Package

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v12

      - name: Setup Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v6

      - name: Run build
        run: |
          nix build --print-build-logs --show-trace

  release-gate:
    name: Release gate

    if: ${{ always() }}

    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: Exit with error
        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
        run: exit 1
